plugin: aws_ec2
regions:
  - eu-central-1
filters:
  tag:Role: wordpress
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: tag_Role
compose:
  ansible_host: private_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'~/.ssh/myDevKey.pem'"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no -o ProxyCommand=\"ssh -i ~/.ssh/myDevKey.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@YOUR_JENKINS_IP\"'"